In [ ]:
# Install numpy in your computer 'pip install numpy', pandas installing command - 'pip install pandas'

In [ ]:
# conda install numpy - for anaconda people, # conda install pandas

In [156]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array((1,6,9))
a

In [ ]:
type(a)

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a.dtype

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

In [ ]:
b.ndim

In [ ]:
b.shape

In [ ]:
b.size

In [ ]:
b.dtype

In [ ]:
c = np.array([[1,2,4], 
              [5,8,7]])
c.dtype

In [ ]:
c

In [ ]:
d = np.array([[1,2,4], [5,8,7]], dtype = 'float')
d.dtype

In [ ]:
d

In [ ]:
e = np.zeros((3,4,2))     #pass the shape of the array you want
e

In [ ]:
f = np.ones((3,4))
f

In [ ]:
g = np.full((3,4), 4, dtype = 'float')
g

In [ ]:
h = np.random.random((3,4))
h

In [ ]:
i = np.arange(4, 37, 5)
i

In [ ]:
j = np.linspace(4, 37, 7)
j

In [ ]:
g = np.full((3,4), 4, dtype = 'complex')
g

In [14]:
c = np.array([[1,2,4,3], 
              [5,8,7,0],
              [1,2,4,3], 
              [5,8,7,0]])
c

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3],
       [5, 8, 7, 0]])

In [ ]:
c.size

In [ ]:
c.shape

In [ ]:
rc = c.reshape(1,4,2,2)
rc

In [ ]:
rc1 = c.reshape(2,2,2,2)
rc1

In [ ]:
rc.shape

In [ ]:
rc.size

In [ ]:
fc = c.flatten(order = 'C')    #Row Major
fc

In [ ]:
fc = c.flatten(order = 'F')    #Column Major
fc

In [4]:
c

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3],
       [5, 8, 7, 0]])

In [5]:
c[[0,2],[3,2]]

array([2, 4])

In [6]:
c[c>3]

array([4, 5, 8, 7, 4, 5, 8, 7])

In [8]:
fc = np.array([[1,3,4,5],
              [6,7,8,9],
              [9,8,7,6],
              [5,4,3,2]])
fc

array([[1, 3, 4, 5],
       [6, 7, 8, 9],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [9]:
fc[[0,2],[0,2]]

array([1, 7])

In [11]:
c = np.array([[1,2,3,4,54,45,40,540],
           [8,7,6,5,54,50,40,50],
           [9,10,11,12,45,2,2,105],
           [16,15,14,13,12,1,201,4],
           [1,2,3,4,54,45,40,540],
           [8,7,6,5,54,50,40,50],
           [9,10,11,12,45,2,2,105],
           [16,15,14,13,12,1,201,4]])
c

array([[  1,   2,   3,   4,  54,  45,  40, 540],
       [  8,   7,   6,   5,  54,  50,  40,  50],
       [  9,  10,  11,  12,  45,   2,   2, 105],
       [ 16,  15,  14,  13,  12,   1, 201,   4],
       [  1,   2,   3,   4,  54,  45,  40, 540],
       [  8,   7,   6,   5,  54,  50,  40,  50],
       [  9,  10,  11,  12,  45,   2,   2, 105],
       [ 16,  15,  14,  13,  12,   1, 201,   4]])

In [12]:
c[[1,2,7],[3,5,0]]

array([ 5,  2, 16])

In [13]:
c[c%2==0]

array([  2,   4,  54,  40, 540,   8,   6,  54,  50,  40,  50,  10,  12,
         2,   2,  16,  14,  12,   4,   2,   4,  54,  40, 540,   8,   6,
        54,  50,  40,  50,  10,  12,   2,   2,  16,  14,  12,   4])

In [15]:
c

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3],
       [5, 8, 7, 0]])

In [19]:
c[:2, 2:]   #c[Row slicing, Column Slicing]

array([[4, 3],
       [7, 0]])

In [22]:
c[::2, ::2]

array([[1, 4],
       [1, 4]])

In [37]:
fc = np.array([[1,3,4,5],
              [6,7,8,9],
              [9,8,7,6],
              [5,4,3,2]])
fc

array([[1, 3, 4, 5],
       [6, 7, 8, 9],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [38]:
fc[[0,0,2],[1,3,1]]

array([3, 5, 8])

In [39]:
fc[0::2,1::2]

array([[3, 5],
       [8, 6]])

In [40]:
fc[0::2][1::2]

array([[9, 8, 7, 6]])

In [41]:
fc[0::2]

array([[1, 3, 4, 5],
       [9, 8, 7, 6]])

In [42]:
fc

array([[1, 3, 4, 5],
       [6, 7, 8, 9],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [50]:
l = np.array([1,2,3,4])
l

array([1, 2, 3, 4])

In [51]:
l += 1    #l = l+1
l

array([2, 3, 4, 5])

In [48]:
l

array([1, 2, 3, 4])

In [52]:
c

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3],
       [5, 8, 7, 0]])

In [53]:
m = np.array([[1, 2, 4, 3],
                [5, 8, 7, 0],
               [1, 2, 4, 3]])
m

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3]])

In [54]:
m.T

array([[1, 5, 1],
       [2, 8, 2],
       [4, 7, 4],
       [3, 0, 3]])

In [59]:
n = np.array([[2, 3, 4, 5]])

In [60]:
n.T

array([[2],
       [3],
       [4],
       [5]])

In [84]:
m

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3]])

In [85]:
m.max()

8

In [86]:
m.max(axis = 0)

array([5, 8, 7, 3])

In [64]:
m.max(axis = 1)

array([4, 8, 4])

In [80]:
m

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3]])

In [83]:
m.cumsum(axis = 0)

array([[ 1,  2,  4,  3],
       [ 6, 10, 11,  3],
       [ 7, 12, 15,  6]], dtype=int32)

In [95]:
m.cumprod(axis = 0)

array([[  1,   2,   4,   3],
       [  5,  16,  28,   0],
       [  5,  32, 112,   0]], dtype=int32)

In [91]:
p = np.array([[1, 4, 7],
             [2, 5, 8],
             [3, 6, 9]])
p

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [89]:
p.max(axis=0)

array([3, 6, 9])

In [92]:
p.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
p.max(axis=0)

array([3, 6, 9])

In [94]:
p

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [2]:
q = np.random.random((3,2))
q

array([[0.35851565, 0.25846081],
       [0.52417122, 0.8339629 ],
       [0.17991277, 0.30998341]])

In [46]:
q1 = np.random.randint(2, 10, (2,3))
q1

array([[8, 3, 6],
       [2, 8, 5]])

In [61]:
q2 = np.random.uniform(2.2, 4.5, (2,3))
q2

4.093586689584551

In [71]:
q3 = np.random.rand()
q3

0.2650113496916401

In [74]:
q3 = np.random.rand(4)
q3

array([0.97698754, 0.34881888, 0.36479628, 0.40256894])

In [99]:
l = [1,2,3,4,5,6,7,8,9,0]
q4 = np.random.choice(l, (2,3))
q4

array([[0, 6, 8],
       [4, 7, 4]])

In [100]:
# import random

In [106]:
a1 = np.array([[1,2],
              [3,4]])
a2 = np.array([[5,6],
              [7,8]])

In [107]:
a1

array([[1, 2],
       [3, 4]])

In [108]:
a2

array([[5, 6],
       [7, 8]])

In [109]:
c = a1+a2     #   -, *, /, //, **, %
c

array([[ 6,  8],
       [10, 12]])

In [111]:
f1 = a1.dot(a2)
f1

array([[19, 22],
       [43, 50]])

In [112]:
a1

array([[1, 2],
       [3, 4]])

In [113]:
a2

array([[5, 6],
       [7, 8]])

In [121]:
np.sin(a1)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [123]:
s = np.array([0, np.pi/2, np.pi])
s

array([0.        , 1.57079633, 3.14159265])

In [124]:
ss = np.sin(s)
ss

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [125]:
a1

array([[1, 2],
       [3, 4]])

In [126]:
np.exp(a1)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [127]:
np.sqrt(a1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [131]:
np.power(a2, a1)

array([[   5,   36],
       [ 343, 4096]], dtype=int32)

In [129]:
a1

array([[1, 2],
       [3, 4]])

In [130]:
a2

array([[5, 6],
       [7, 8]])

In [132]:
a = np.array([[1,4,2],
             [3,4,6],
             [0,-1,5]])
a

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

In [136]:
np.sort(a, axis = 0)  #axis, 0, 1, None for 2-dimensional array

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [137]:
np.sort(a)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [138]:
np.sort(a, axis = 1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [145]:
dt = [('name', 'S5'), ('Grad year', int), ('CGPA', float)]

In [151]:
x = np.array([('d', 2009, 8.5),
              ('b', 2010, 8.5), 
              ('c', 2008, 9)], dtype = dt)
x

array([(b'd', 2009, 8.5), (b'b', 2010, 8.5), (b'c', 2008, 9. )],
      dtype=[('name', 'S5'), ('Grad year', '<i4'), ('CGPA', '<f8')])

In [155]:
np.sort(x, order = ['name', 'CGPA'])

array([(b'b', 2010, 8.5), (b'c', 2008, 9. ), (b'd', 2009, 8.5)],
      dtype=[('name', 'S5'), ('Grad year', '<i4'), ('CGPA', '<f8')])

# Pandas

In [157]:
#Creating Series through list
l = [2,4,0,4,1]
s = pd.Series(l)
s

0    2
1    4
2    0
3    4
4    1
dtype: int64

In [158]:
# Creating DataFrame through list
li = [[1,2],
      [3,4],
      [5,6]]
df = pd.DataFrame(li)
df

0  1
0  1  2
1  3  4
2  5  6

In [165]:
li = [[1,2],
      [3,4],
      [5,6]]
df = pd.DataFrame(li, columns = ['First', 'Second'], index = ['a','b','c'])
df

First  Second
a      1       2
b      3       4
c      5       6

In [167]:
# Creating DataFrame through dictionary
d = {"First":[1,3,5],
    "Second":[2,4,6]}
dfd = pd.DataFrame(d, index = [9, 6, 2])
dfd

First  Second
9      1       2
6      3       4
2      5       6

In [168]:
# Creating DataFrame from list of dictionaries
ld = [{1:2, 3:4, 5:6},
      {1:7, 3:8, 5:9}]
dfld = pd.DataFrame(ld)
dfld

1  3  5
0  2  4  6
1  7  8  9

In [170]:
d = {'First':[1,3,5],
  'Second':[2,4,6]}
df = pd.DataFrame(d, index=[5,4,9])
df

First  Second
5      1       2
4      3       4
9      5       6

In [171]:
df.T

5  4  9
First   1  3  5
Second  2  4  6

In [172]:
df

First  Second
5      1       2
4      3       4
9      5       6

In [173]:
df.to_csv("some.csv")          # df.to_excel("some.xlsx") - to save in excel format

In [174]:
rc = pd.read_csv('nba.csv')    # C:/Users/harsh/Documents/Python Codes/DataScience SkillSlash Classes/nba.csv
rc

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
452           Kentucky  2239800.0  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  

[457 rows x 9 columns]

In [176]:
v = pd.read_excel("nba1.xlsx")
v

Name            Team  Number Position  Age               Height  \
0    Avery Bradley  Boston Celtics       0       PG   25  2021-02-06 00:00:00   
1      Jae Crowder  Boston Celtics      99       SF   25  2021-06-06 00:00:00   
2     John Holland  Boston Celtics      30       SG   27  2021-05-06 00:00:00   
3      R.J. Hunter  Boston Celtics      28       SG   22  2021-05-06 00:00:00   
4    Jonas Jerebko  Boston Celtics       8       PF   29  2021-10-06 00:00:00   
..             ...             ...     ...      ...  ...                  ...   
452     Trey Lyles       Utah Jazz      41       PF   20  2021-10-06 00:00:00   
453   Shelvin Mack       Utah Jazz       8       PG   26  2021-03-06 00:00:00   
454      Raul Neto       Utah Jazz      25       PG   24  2021-01-06 00:00:00   
455   Tibor Pleiss       Utah Jazz      21        C   26  2021-03-07 00:00:00   
456    Jeff Withey       Utah Jazz      24        C   26                  7-0   

     Weight            College     Salary  
0       180              Texas  7730337.0  
1       235          Marquette  6796117.0  
2       205  Boston University        NaN  
3       185      Georgia State  1148640.0  
4       231                NaN  5000000.0  
..      ...                ...        ...  
452     234           Kentucky  2239800.0  
453     203             Butler  2433333.0  
454     179                NaN   900000.0  
455     256                NaN  2900000.0  
456     231             Kansas   947276.0  

[457 rows x 9 columns]