In [ ]:
# Install numpy in your computer pip install numpy

In [ ]:
# conda install numpy - for anaconda people

In [1]:
import numpy as np

In [ ]:
a = np.array((1,6,9))
a

In [ ]:
type(a)

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a.dtype

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

In [ ]:
b.ndim

In [ ]:
b.shape

In [ ]:
b.size

In [ ]:
b.dtype

In [ ]:
c = np.array([[1,2,4], 
              [5,8,7]])
c.dtype

In [ ]:
c

In [ ]:
d = np.array([[1,2,4], [5,8,7]], dtype = 'float')
d.dtype

In [ ]:
d

In [ ]:
e = np.zeros((3,4,2))     #pass the shape of the array you want
e

In [ ]:
f = np.ones((3,4))
f

In [ ]:
g = np.full((3,4), 4, dtype = 'float')
g

In [ ]:
h = np.random.random((3,4))
h

In [ ]:
i = np.arange(4, 37, 5)
i

In [ ]:
j = np.linspace(4, 37, 7)
j

In [ ]:
g = np.full((3,4), 4, dtype = 'complex')
g

In [14]:
c = np.array([[1,2,4,3], 
              [5,8,7,0],
              [1,2,4,3], 
              [5,8,7,0]])
c

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3],
       [5, 8, 7, 0]])

In [ ]:
c.size

In [ ]:
c.shape

In [ ]:
rc = c.reshape(1,4,2,2)
rc

In [ ]:
rc1 = c.reshape(2,2,2,2)
rc1

In [ ]:
rc.shape

In [ ]:
rc.size

In [ ]:
fc = c.flatten(order = 'C')    #Row Major
fc

In [ ]:
fc = c.flatten(order = 'F')    #Column Major
fc

In [4]:
c

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3],
       [5, 8, 7, 0]])

In [5]:
c[[0,2],[3,2]]

array([2, 4])

In [6]:
c[c>3]

array([4, 5, 8, 7, 4, 5, 8, 7])

In [8]:
fc = np.array([[1,3,4,5],
              [6,7,8,9],
              [9,8,7,6],
              [5,4,3,2]])
fc

array([[1, 3, 4, 5],
       [6, 7, 8, 9],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [9]:
fc[[0,2],[0,2]]

array([1, 7])

In [11]:
c = np.array([[1,2,3,4,54,45,40,540],
           [8,7,6,5,54,50,40,50],
           [9,10,11,12,45,2,2,105],
           [16,15,14,13,12,1,201,4],
           [1,2,3,4,54,45,40,540],
           [8,7,6,5,54,50,40,50],
           [9,10,11,12,45,2,2,105],
           [16,15,14,13,12,1,201,4]])
c

array([[  1,   2,   3,   4,  54,  45,  40, 540],
       [  8,   7,   6,   5,  54,  50,  40,  50],
       [  9,  10,  11,  12,  45,   2,   2, 105],
       [ 16,  15,  14,  13,  12,   1, 201,   4],
       [  1,   2,   3,   4,  54,  45,  40, 540],
       [  8,   7,   6,   5,  54,  50,  40,  50],
       [  9,  10,  11,  12,  45,   2,   2, 105],
       [ 16,  15,  14,  13,  12,   1, 201,   4]])

In [12]:
c[[1,2,7],[3,5,0]]

array([ 5,  2, 16])

In [13]:
c[c%2==0]

array([  2,   4,  54,  40, 540,   8,   6,  54,  50,  40,  50,  10,  12,
         2,   2,  16,  14,  12,   4,   2,   4,  54,  40, 540,   8,   6,
        54,  50,  40,  50,  10,  12,   2,   2,  16,  14,  12,   4])

In [15]:
c

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3],
       [5, 8, 7, 0]])

In [19]:
c[:2, 2:]   #c[Row slicing, Column Slicing]

array([[4, 3],
       [7, 0]])

In [22]:
c[::2, ::2]

array([[1, 4],
       [1, 4]])

In [37]:
fc = np.array([[1,3,4,5],
              [6,7,8,9],
              [9,8,7,6],
              [5,4,3,2]])
fc

array([[1, 3, 4, 5],
       [6, 7, 8, 9],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [38]:
fc[[0,0,2],[1,3,1]]

array([3, 5, 8])

In [39]:
fc[0::2,1::2]

array([[3, 5],
       [8, 6]])

In [40]:
fc[0::2][1::2]

array([[9, 8, 7, 6]])

In [41]:
fc[0::2]

array([[1, 3, 4, 5],
       [9, 8, 7, 6]])

In [42]:
fc

array([[1, 3, 4, 5],
       [6, 7, 8, 9],
       [9, 8, 7, 6],
       [5, 4, 3, 2]])

In [50]:
l = np.array([1,2,3,4])
l

array([1, 2, 3, 4])

In [51]:
l += 1    #l = l+1
l

array([2, 3, 4, 5])

In [48]:
l

array([1, 2, 3, 4])

In [52]:
c

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3],
       [5, 8, 7, 0]])

In [53]:
m = np.array([[1, 2, 4, 3],
                [5, 8, 7, 0],
               [1, 2, 4, 3]])
m

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3]])

In [54]:
m.T

array([[1, 5, 1],
       [2, 8, 2],
       [4, 7, 4],
       [3, 0, 3]])

In [59]:
n = np.array([[2, 3, 4, 5]])

In [60]:
n.T

array([[2],
       [3],
       [4],
       [5]])

In [84]:
m

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3]])

In [85]:
m.max()

8

In [86]:
m.max(axis = 0)

array([5, 8, 7, 3])

In [64]:
m.max(axis = 1)

array([4, 8, 4])

In [80]:
m

array([[1, 2, 4, 3],
       [5, 8, 7, 0],
       [1, 2, 4, 3]])

In [83]:
m.cumsum(axis = 0)

array([[ 1,  2,  4,  3],
       [ 6, 10, 11,  3],
       [ 7, 12, 15,  6]], dtype=int32)

In [95]:
m.cumprod(axis = 0)

array([[  1,   2,   4,   3],
       [  5,  16,  28,   0],
       [  5,  32, 112,   0]], dtype=int32)

In [91]:
p = np.array([[1, 4, 7],
             [2, 5, 8],
             [3, 6, 9]])
p

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [89]:
p.max(axis=0)

array([3, 6, 9])

In [92]:
p.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
p.max(axis=0)

array([3, 6, 9])

In [94]:
p

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])